Arrow spacing rule
netsells/eslint-config-netsells pull request #11
Opened 2018-02-06 14:30 UTC by martin91s

## Suggested rule/changes(s):
* `<arrow-spacing>` 

## Reason for addition/amendment

Before and after the arrow function's arrow, should always include spacing. 
for example: (a) => {}.

Both before and after should be set as true.
{ "before": true, "after": true }.

This helps the code to be more readable.

Feel free to include code samples if it's a new rule.

@netsells/frontend - Please review

2018-02-06 14:55 UTC, samturrell requested changes

2018-02-06 14:55 UTC, samturrell commented on rules/javascript.js
> +        //
Give a quick blurb :D

2018-02-06 14:55 UTC, samturrell commented on rules/javascript.js
> +        'arrow-spacing': [_THROW.ERROR, {before: true, after: true}],
Drop things down onto new lines e.g.:
```js
'arrow-spacing': [_THROW.ERROR, {
    before: true, 
    after: true,
}],
```

2018-02-07 13:58 UTC, samturrell approved these changes

2018-02-07 13:58 UTC, samturrell commented on readme.md
> +<<<<<<< HEAD
Nooooooooooooooooo

2018-02-07 13:58 UTC, samturrell commented on readme.md
> +<<<<<<< HEAD
noooooooooo

2018-02-07 13:58 UTC, samturrell commented on readme.md
> +<<<<<<< HEAD
Nooooooooo

2018-02-07 14:00 UTC, wik-z commented on readme.md
> +<<<<<<< HEAD
Nooooooooooooooooo

2018-02-07 17:46 UTC, samturrell requested changes

2018-02-07 17:46 UTC, samturrell commented on readme.md
> +`var count = posts.length;
I don't think you've fixed this properly

2018-02-08 09:45 UTC, samturrell approved these changes

2018-02-11 23:28 UTC, merged