Rule/yoda
netsells/eslint-config-netsells pull request #35
Opened 2018-02-07 17:43 UTC by rowancollins89

## Suggested rule/changes(s):
* `<yoda>` 

## Reason for addition/amendment
Discourage code typed like yoda would speak

```
if ("red" === colour) {
    //...
}
```

@netsells/frontend - Please review

2018-02-07 17:45 UTC, wik-z commented
An important rule, this is.

2018-02-07 17:45 UTC, samturrell requested changes
I like it

2018-02-07 17:45 UTC, samturrell commented on rules/javascript.js
> +            'exceptRange': true,
no quotes

2018-02-07 17:45 UTC, samturrell commented on readme.md
> +if ("red" === color) {
single quotes

2018-02-07 17:45 UTC, samturrell commented on readme.md
> +if (value === "red") {
single quotes (should make this a linter rule)

2018-02-08 09:10 UTC, samturrell approved these changes

2018-02-11 22:27 UTC, merged