Adds no-else-return rule
netsells/eslint-config-netsells pull request #45
Opened 2018-02-07 19:31 UTC by BeccaAnderton18

## Suggested rule/changes(s):
* `<no-else-return>` 

## Reason for addition/amendment
* Closes #29 
* Disallows return statements prior to an else if or else statement
* See examples of code in readme.md
* Also doesn't allow else statements - sorry boys!

@netsells/frontend - Please review

2018-02-07 19:45 UTC, rowancollins89 commented
Me no liek. why cant I return?

2018-02-07 19:47 UTC, BeccaAnderton18 commented
@rowancollins89 you can. Just not before an else / else if. Else / else if's a gross anyway and we should be avoiding them wherever possible. There's also no point returning in an else because it would be the last thing to return anyway.

2018-02-07 19:54 UTC, rowancollins89 commented
its past my bed time. I'm being thick.
```
if(foo !== bar) {
    return foo;
}
return bar;
```

would work so i'm happy.

2018-02-07 19:56 UTC, BeccaAnderton18 commented
@rowancollins89 you are correct - although you'd need a space after than if 😉

2018-02-08 09:55 UTC, samturrell approved these changes

2018-02-08 19:22 UTC, samturrell requested changes

2018-02-08 19:22 UTC, samturrell commented on rules/javascript.js
> +        'no-else-return': [_THROW.WARNING, {
Comment

2018-02-08 19:22 UTC, samturrell commented on rules/javascript.js
> +        }]
Trailing comma pls

2018-02-09 09:09 UTC, BeccaAnderton18 commented
@samturrell fixed these!

2018-02-09 09:10 UTC, samturrell commented
doesn't look liek it

2018-02-09 09:12 UTC, BeccaAnderton18 commented
@samturrell I did. But you'd pushed to this branch last night. So my push failed. Check again.

2018-02-09 09:14 UTC, samturrell approved these changes

2018-02-09 09:14 UTC, merged