Adds no-alert rule
netsells/eslint-config-netsells pull request #48
Opened 2018-02-07 20:29 UTC by wik-z

## Suggested rule/changes(s):
* `<no-alert>` 

## Reason for addition/amendment
Disallows alert() function

@netsells/frontend - Please review

2018-02-08 08:58 UTC, rowancollins89 commented
@wik-z should be a warning in my opinion as some people do sometimes use Alert Driven Development.

2018-02-08 08:59 UTC, BeccaAnderton18 commented
@rowancollins89 people should probably not be doing Alert Driven Development 🤔

2018-02-08 09:00 UTC, samturrell commented
@BeccaAnderton18 probably not, but it's a solid technique when wits end 😂

2018-02-08 09:04 UTC, jdtjenkins commented
Could this rule somehow get an env variable for dev or production builds? Warning in dev, error in production?

2018-02-08 09:08 UTC, samturrell commented
@jdtjenkins Possibly! Could be possible to use something like https://www.npmjs.com/package/dotenv to read the env and then return accordingly

2018-02-08 09:12 UTC, wik-z commented
@samturrell I think @jdtjenkins wanted to say is that it should throw a warning when the NODE_ENV is set to development and a warning when it's in production. I agree with that!

2018-02-08 09:17 UTC, samturrell commented
Ah, sorry node env, not normal env. In which case yes, you definitely can `process.env.NODE_ENV` i believe

2018-02-08 09:35 UTC, jdtjenkins commented
@samturrell @wik-z Yeah sorry the NODE env, which also already gets set by laravel mix

2018-02-08 09:37 UTC, samturrell commented
@jdtjenkins Yep, as per above. However let's try not to use laravel mix as examples and dependencies as this package should be build tool agnostic. However NODE_ENV _should_ be available in all instances in some regard, otherwise fallback to dev

2018-02-08 12:02 UTC, wik-z commented
Just added an 'Utils' class, with a 'isProduction' method which basically checks if we're in the production env. Tested this on node 6.5 and it worked like a charm, so if it doesn't work for you, it might be worth checking which node version you're using. 

The first idea was to make it a simple function:
```
export function isProduction() {
    return process.env.NODE_ENV === 'production';
}
```

but because we can't use `import`/`export` syntax with CommonJS, I would have to export an object of functions:

```
module.exports = {
    isProduction: function() {
        return process.env.NODE_ENV === 'production';
    }
}
```

This would get really messy in the future though, so the better option is to define the functions separately in this module and then just put them in an object we want to export:

```
function isProduction() {
    return process.env.NODE_ENV === 'production';
}

module.exports = {
    isProduction,
};
```

and that would work, especially that #5 wasn't approved. However, it looks like Node supports classes, so we tried this option, which I personally think is a better and a cleaner practice. It would be great to hear what people think though.

2018-02-08 13:14 UTC, jdtjenkins commented
Think this looks really good. Let's you use Alert Driven Development and also stops them leaking into production. Also that's a pretty fancy class

2018-02-08 13:17 UTC, rowancollins89 commented
yeah think this should be merged first @samturrell then we can adjust other PRs to allow warnings in dev but errors in prod

2018-02-08 13:21 UTC, jdtjenkins commented
Hmmm then is it worth taking this idea further and specifying two different linting arrays for production and dev? Or three? `dev`, `prod` and `both` ?

2018-02-08 13:36 UTC, samturrell commented
Personally I'm a bigger fan of the functional approach for helper/utils, but i'll leave that up to everyone else to decide. (classes also provide a lot more overhead than a functional return and can be harder to share logic between multiple classes) I don't want this to be used too much though for other rules as it will be an absolute minefield on older codebases, and people will just never be able to push code again until hours have been spent fixing linter issues. I think errors should be reserved for things that DEFINITELY shouldn't make it into production. Stuff that users will see. Only real contenders for it would be alerts and debuggers, potentially console statements to a lesser extent.

2018-02-08 14:50 UTC, jdtjenkins commented
I was thinking something along these lines. This would like you just add a rule to the relevant array instead of using conditionals in the rules itself. This also means if we ever wanted to re-condition a set of rules we don't have to go through and change every rule, we can just change what condition that array is being brought in on.

```js
let rules = [
    'no-var': _THROW.ERROR,
]

let developementRules = [
    'no-alert': _THROW.WARNING,
]

let productionRules = [
    'no-alert': _THROW.ERROR,
]

if (process.env.NODE_ENV === 'production'){
    module.exports = [
        ...rules,
        ...productionRules,
    ]
} else {
    module.exports = [
        ...rules,
        ...developmentRules,
    ]
}
```

2018-02-08 19:19 UTC, samturrell commented
Again though, i think it's only really useful for those few rules that stop user-facing issues e.g. alerts, debuggers, console.

2018-02-16 09:21 UTC, rowancollins89 commented
@jdtjenkins @wik-z whats happening with this PR?

2018-02-16 09:23 UTC, jdtjenkins commented
@wik-z @rowancollins89 I think leave out the class or arrays idea for now and we can just add a check for process.ENV on a rule per rule basis.

2018-02-16 09:40 UTC, wik-z commented
Yea i'll leave the first idea.
If people could just vote which way to do it: class or functions?

Currently the `isProduction` method (and all future methods) is in the Utils class (see code for reference), but we can just export/import the utils functions separately from the file if we want, using module.export.

functions example:
```
module.exports.isProduction = () => {
   return someLogic;
}
```


Upvote for class, downvote for functions

2018-02-20 11:18 UTC, samturrell requested changes

2018-02-20 11:18 UTC, samturrell commented on readme.md
> +#### 📍 no-implicit-coercion
You haven't change the rule name

2018-02-20 11:18 UTC, samturrell commented on rules/javascript.js
> +    }
Leave the comma dangle

2018-02-20 11:58 UTC, samturrell approved these changes

2018-02-20 11:58 UTC, merged