add jquery global to env
netsells/eslint-config-netsells pull request #55
Opened 2018-02-12 11:51 UTC by rowancollins89

## Suggested rule/changes(s):
 title says it all. currently getting issues with `'$' is not defined` all over the place. 

@netsells/frontend - Please review

2018-02-12 11:52 UTC, samturrell commented
I don't think that's right

2018-02-12 13:24 UTC, rowancollins89 commented
@samturrell happy now?

2018-02-12 13:25 UTC, samturrell commented
`npm run lint`

2018-02-12 14:06 UTC, samturrell requested changes

2018-02-12 14:06 UTC, samturrell commented on index.js
> +        node: true
comma

2018-02-12 14:06 UTC, samturrell commented on index.js
> +        $: true
comma

2018-02-12 14:23 UTC, samturrell submitted a review, later dismissed

2018-02-12 14:23 UTC, samturrell commented on package.json
> +    "lint": "eslint ./ndex.js ./rules/**/*.js --fix"
`ndex`

2018-02-14 09:03 UTC, samturrell commented
Just checked the docs for this and i think you were actually right the first time...

2018-02-14 11:21 UTC, samturrell requested changes

2018-02-14 11:21 UTC, samturrell commented on index.js
> +        jquery: true,
should be in env 🤦‍♂️

2018-02-15 22:17 UTC, samturrell approved these changes

2018-02-15 22:17 UTC, merged