Require a space before function parenthesis
netsells/eslint-config-netsells pull request #61
Opened 2018-02-15 22:32 UTC by neveena

## Suggested rule/changes(s):
* `<space-before-function-paren>` : `WARNING`

## Reason for addition/amendment
>This rule aims to enforce consistent spacing before function parentheses and as such, will warn whenever whitespace doesn’t match the preferences specified.

@netsells/frontend - Please review

2018-02-15 22:36 UTC, samturrell commented
Oo an interesting one! This may start some debates

![](https://media1.tenor.com/images/6da6e563530b67bc743f6831e1656f11/tenor.gif)

2018-02-16 08:48 UTC, BeccaAnderton18 commented
I am not okay with this 😩

2018-02-16 08:49 UTC, martin91s commented
me neither, don't expect many thumbs up from this Neveena :D haha

2018-02-16 08:51 UTC, Juddling commented
Boooooo

2018-02-16 08:51 UTC, samturrell commented
I love it.

2018-02-16 08:51 UTC, wik-z commented
Booooooo

2018-02-16 08:52 UTC, rowancollins89 commented
Booooooooo

2018-02-16 08:52 UTC, BeccaAnderton18 commented
Majority rules @samturrell

2018-02-16 08:52 UTC, jdtjenkins commented
Yeah I'm not sure about this one, I agree with a consistent style... Just... Not this one

2018-02-16 08:52 UTC, samturrell commented
MajoriTEE

2018-02-16 08:53 UTC, wik-z commented
let democracy win

2018-02-16 08:53 UTC, samturrell commented
var democracy win

2018-02-16 08:55 UTC, Juddling requested changes
Pls remove that space

2018-02-16 08:56 UTC, BeccaAnderton18 commented
Set this one to 'false' @neveena 🙈

2018-02-16 08:58 UTC, samturrell commented
May as well do this while we're at it, you space phobics

```let bar=function(){/* derp */};```

2018-02-16 08:58 UTC, BeccaAnderton18 commented
Don't be so dramatic @samturrell

2018-02-16 09:00 UTC, rowbi-wan requested changes

2018-02-16 09:00 UTC, rowancollins89 commented on rules/javascript.js
> +        'space-before-function-paren': _THROW.WARNING,
please change to `'space-before-function-paren': [_THROW.WARNING, 'never'],`

2018-02-16 09:09 UTC, neveena commented
@BeccaAnderton18 @rowancollins89 @martin91s @wik-z , I guess majority wins 🙊  Im with the team

2018-02-20 11:19 UTC, samturrell approved these changes

2018-02-20 11:19 UTC, merged